# Generated by Django 2.0 on 2017-12-20 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20171220_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='comment',
            field=models.ManyToManyField(blank=True, related_name='article_comment', to='blog.Comment'),
        ),
    ]
